### ISSUE TITLE
Develop a SaveCredentials screen

### ISSUE THREAD

**Issue by fifthsegment** [fifthsegment/byos#13]
1- Use MUI as the design system
2- After login the application should save this data into `ApplicationContext`

Sample page: https://mui.com/material-ui/getting-started/templates/sign-in/

**Comment by fifthsegment** [comment]
@NaumanNazir  Lets modify this task into this:

![Image](https://user-images.githubusercontent.com/5513549/194123081-9b26b06a-a1cb-48fa-8ff7-09df55ba685b.png)

**Comment by NaumanNazir** [comment]
Updated login page and modal. (WIP)

**Comment by fifthsegment** [comment]
@NaumanNazir Jani your PR got merged, can you please make a new PR for the Bucket field?
